### ISSUE TITLE
modernc.org/sqlite

### ISSUE THREAD

**Issue by gedw99** [mtlynch/logpaste#117]
Have you had any luck using "modernc.org/sqlite" with litestream yet, or its not compelling ?

**Comment by mtlynch** [comment]
I've never heard of it. Feel free to reopen if you'd like to share ways that it can be useful to logpaste.

**Comment by gedw99** [comment]
"modernc.org/sqlite" is the same as the "github.com/mattn/go-sqlite3 " SQLITE for goalng, but ""modernc.org/sqlite" is without CGO. So much easier to run everywhere.
It is a bit slower than the with CGO version of golang sqlite. 
Ben at LiteStream has not used it yet....
