### ISSUE TITLE
Feature request: Dark mode.

### ISSUE THREAD

**Issue by KoxSosen** [mtlynch/logpaste#120]
Hello! 

I recently discovered logpaste, and it's a pleasure to use so far. Easy to set up, self host, and use! 
However, the text isn't always the easiest to read because of the white background on the home page. 
May can I ask, would it be possible to add dark mode, which can be enabled using a docker environment value?

**Comment by mtlynch** [comment]
Sure, that's a good idea!

**Comment by mtlynch** [comment]
Hmmm, I realized this is trickier than I expected. When you view a paste, the browser is just showing raw text without any HTML or CSS, so we can't change the style easily.

I can make a dark mode for the home page. Would that work for what you have in mind?

https://github.com/mtlynch/logpaste/pull/121

![image](https://user-images.githubusercontent.com/7783288/140645916-7bc86ee4-3dfa-4781-aeb7-c347e187beb0.png)

**Comment by KoxSosen** [comment]
Yup, that's exactly what I imagined. Thank you so much!
