### ISSUE TITLE
Add option to force HTTPS

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/logpaste#124]
One small thing to mention: When using curl to upload text, the output URL defaults to http. Most webservers should already redirect from port 80 to port 443, but I think it would be nice to add an option to enable https everywhere instead of the http output.

_Originally posted by @KoxSosen in https://github.com/mtlynch/logpaste/issues/121#issuecomment-963351527_

**Comment by KoxSosen** [comment]
Hello! Thank you for implementing this feature.
