### ISSUE TITLE
Do not assume S3

### ISSUE THREAD

**Issue by steren** [mtlynch/logpaste#133]
I successfully deployed logpaste to Google Cloud on Google Cloud Run and Google Cloud Storage

I had the change the code in the following way:

- Remove [these 3 lines](https://github.com/mtlynch/logpaste/blob/6751f1adef3fa4e74c17a6b6df98640f7324557e/litestream.yml#L1-L3) from `litestream.yml` since litestream is able to pick up credentials from the environment directly
- Update [the logic to decide to use litestream](https://github.com/mtlynch/logpaste/blob/6751f1adef3fa4e74c17a6b6df98640f7324557e/docker_entrypoint#L48-L51)

Then, I built with Cloud Build `gcloud builds submit . --tag gcr.io/<PROJECT>/logpaste:latest`

And deployed to Cloud Run: `gcloud beta run deploy logpaste --image gcr.io/<PROJECT>/logpaste:latest --set-env-vars DB_REPLICA_URL=gcs://<BUCKET>/db --execution-environment gen2 --no-cpu-throttling` 

I can try to send a PR: we can enable litestream if `DB_REPLICA_URL` is set, but I'm not sure about the best way handle the translation of envvars to `litestream.yml`

**Comment by mtlynch** [comment]
Thanks for reporting this and sharing the Google Cloud Run steps, @steren!

I tried your instructions, and it's pretty cool running it on Cloud Run. I was able to deploy successfully after #134 without removing the `LITESTREAM` lines from `litestream.yml`. Do you run into issues with those lines?

I'm adding instructions for Cloud Run here: #135

**Comment by steren** [comment]
Great to hear the changes to litestream.yml aren't needed, I guess they aren't picked up if the values are empty.

I left a med comments on the guide. Thanks for writing!
