### ISSUE TITLE
[Feature] Automatic light/dark theme based on system theme

### ISSUE THREAD

**Issue by Kangie** [mtlynch/logpaste#175]
I've run up a small instance for some users and the one "complaint" that I've had is that it's light or dark theme only. Modern websites and browsers can check for the system theme - would it be possible to do similar here?

I'm a little broken atm but will try to look at this in a few months (fingers crossed)

**Comment by Kangie** [comment]
A stretch goal for this one would be the ability for users to toggle light/dark theme on a single click and for that to be saved, probably using a cookie but I don't want to lock that in as a mechanism. :)

**Comment by mtlynch** [comment]
Yeah, this would be doable. We could add an option for the `-darkmode` flag like `auto` and then use the `@media (prefers-color-scheme: dark)` [media query](https://css-tricks.com/dark-modes-with-css/) to show the right theme.

If someone contributed this, I'd accept the change, but I likely won't have bandwidth to add this for a while.
