### ISSUE TITLE
Add litestream health check

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/logpaste#72]
If logpaste expects litestream to be replicating data, and it's not, it should fail hard so that users stop uploading logs that will never be replicated.

Maybe the Go app can have a periodic check similar to what's mentioned [in this Kubernetes example](https://github.com/benbjohnson/litestream/issues/28#issuecomment-800955151) and panic if litestream is no longer replicating.

**Comment by Panzki** [comment]
Hi Michael,
I just read your blog post on Litestream and found it really interesting, thanks. If you still want to tackle this issue a Docker health check could be helpful ([link to docs](https://mtlynch.io/litestream/)). Maybe you could build a health check that kills the container if Litestream stops working. The hosting platform would need to take care of spinning up a new container though, which could lead to some downtime.
This was just a quick idea that came to my mind, and maybe it's helpful to you. Thanks again for the great content on your blog.

**Comment by mtlynch** [comment]
Thanks for reading!

>If you still want to tackle this issue a Docker health check could be helpful ([link to docs](https://mtlynch.io/litestream/)). 

I think you may have included the wrong link because that points back to my blog post.

I was thinking of migrating to the [s6 model](https://github.com/benbjohnson/litestream-s6-example), but I haven't looked into it too carefully yet, so I'm not sure if that would be enough or I'd still need health checks.

**Comment by Panzki** [comment]
Sorry, I made a copy and past error. [This is the correct link](https://docs.docker.com/engine/reference/builder/#healthcheck).

The s6 model approach is properly more solid. I never worked if it and from a first look it comes at the price of higher complexity.

**Comment by mtlynch** [comment]
Fixed in #115
